In [3]:
# Enable interactive plot
%matplotlib notebook

<font size="5"> **(Testing) point of application** </font>

Find relevant point of application based on F and M values. 

In [101]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from mpl_toolkits.mplot3d.art3d import Poly3DCollection
from scipy.optimize import minimize, Bounds
import random

In [147]:
r_test = np.array([0.1, -0.10, 0])
F_test = np.array([0, 9, -3])

M_test = np.cross(r_test, F_test)
print('r:',  r_test)

r: [ 0.1 -0.1  0. ]


In [148]:
orig = np.array([0.0, 0.0, 0])

In [149]:
def func(r, F, M, orig):
    return np.linalg.norm(np.cross(r - orig, F) - M)

In [150]:
bounds_x = (-0.15, 0.15)
bounds_y = (-0.15, 0.15)
bounds_z = (0, 0)

In [151]:
# initial guess
r0 = np.array([0.00, 0.0, 0])

# find r that minimizes the objective function
res = minimize(func, r0, 
               args=(F_test, M_test, orig), 
               method='Nelder-Mead', 
               bounds=(bounds_x, bounds_y, bounds_z))
r_min = res.x

print(r_min)

[ 0.09999747 -0.09995743  0.        ]


**Optimizer / minimiser set up**

In [59]:
# dimensions of the block
length = 30/1000
width = 30/1000
height = 2.5/1000

In [60]:
# Moments
Mx = random.randint(0, 10)
My = random.randint(0, 10)
Mz = random.randint(0, 10)

# Forces
Fx = random.randint(0, 10)
Fy = random.randint(0, 10)
Fz = random.randint(0, 10)

M = np.array([Mx, My, Mz])
F = np.array([Fx, Fy, Fz])
orig = np.array([0, 0, 0])

print(M)
print(F)

[7 0 0]
[1 6 4]


In [61]:
# objective function to minimize
def func(r, F, M, orig):
    return np.linalg.norm(np.cross(r - orig, F) - M)

In [62]:
# initial guess
r0 = np.array([0.0, 0.0, 0])

# find r that minimizes the objective function
res = minimize(func, r0, args=(F, M, orig), method='BFGS')
r_min = res.x
print(r_min)

[-1.41880237e-07  5.28301077e-01 -7.92453373e-01]
